### ISSUE TITLE
Does the plugin supports other languages ?

### ISSUE THREAD

**Issue by baimamboukar** [joshpetit/bible#6]
Amazing work @joshpetit 🎉! I really like this....
I have been looking for a similar Rest API or flutter package. This is definitely the best I have found so far.
But, does this packages support other languages ? Especially local languages like fulfulde-adamawa, bassa, lingala .....

Thanks in advance!

**Comment by joshpetit** [comment]
Hey! I'm glad that you found this good, I made it quite a while ago so probably has a lot of changes that could improve it haha.

This is an API wrapper for a few different APIs, so whatever versions the APIs I have listed in the README support are what this package is able to support. You can look at the documentation of the APIs to see if they contain a translation that you would like to use.

If none of them do, see if you can find an API that has the translation you'd like and you can open an issue and one of us could add it to the package.

**Comment by baimamboukar** [comment]
Alright! Thanks for replying

**Comment by joshpetit** [comment]
No worries!
